---
- name: Install package for bundle install
  yum: name={{ item }} state=latest
  with_items:
    - sqlite-devel
    - gcc-c++ #Need for therubyracer install
- name: Update all packages
  yum: name=* state=latest
